config system dhcp relay
    edit "VLAN10"
        set interface "VLAN10-ADMIN"
        set server-ip 10.20.10.10
    next
    edit "VLAN20"
        set interface "VLAN20-VOIP"
        set server-ip 10.20.10.10
    next
    edit "VLAN30"
        set interface "VLAN30-IOT"
        set server-ip 10.20.10.10
    next
    edit "VLAN50"
        set interface "VLAN50-PC"
        set server-ip 10.20.10.10
    next
    edit "VLAN100"
        set interface "VLAN100-GUEST"
        set server-ip 10.20.10.10
    next
    edit "VLAN200"
        set interface "VLAN200-WIFI"
        set server-ip 10.20.10.10
    next
    edit "VLAN300"
        set interface "VLAN300-CAMERAS"
        set server-ip 10.20.10.10
    next
end
