config firewall policy
    edit 10
        set name "LAN-to-Internet"
        set srcintf "VLAN50-PC"
        set dstintf "wan1"
        set srcaddr "all"
        set dstaddr "all"
        set action accept
        set schedule "always"
        set service "ALL"
        set nat enable
    next
    edit 20
        set name "Admin-to-Infra"
        set srcintf "VLAN10-ADMIN"
        set dstintf "VLAN30-IOT"
        set srcaddr "admins"
        set dstaddr "iot-services"
        set action accept
        set schedule "always"
        set service "PING" "HTTP" "HTTPS" "SSH"
    next
    edit 30
        set name "IoT-to-Internet"
        set srcintf "VLAN30-IOT"
        set dstintf "wan1"
        set srcaddr "iot-segment"
        set dstaddr "all"
        set action accept
        set schedule "always"
        set service "HTTP" "HTTPS" "NTP"
        set nat enable
    next
    edit 40
        set name "Guest-Internet"
        set srcintf "VLAN100-GUEST"
        set dstintf "wan1"
        set srcaddr "all"
        set dstaddr "all"
        set action accept
        set schedule "always"
        set service "HTTP" "HTTPS" "DNS"
        set nat enable
    next
end
