config system interface
    edit "agg-core"
        set vdom "root"
        set type aggregate
        set member "port1" "port2"
        set lacp-mode active
        set description "LAG vers Cisco 2960X"
    next
    edit "VLAN10-ADMIN"
        set interface "agg-core"
        set vlanid 10
        set ip 10.20.10.254 255.255.255.0
        set allowaccess ping https ssh snmp
    next
    edit "VLAN20-VOIP"
        set interface "agg-core"
        set vlanid 20
        set ip 10.20.20.254 255.255.255.0
    next
    edit "VLAN30-IOT"
        set interface "agg-core"
        set vlanid 30
        set ip 10.20.30.254 255.255.255.0
    next
    edit "VLAN50-PC"
        set interface "agg-core"
        set vlanid 50
        set ip 10.20.50.254 255.255.255.0
    next
    edit "VLAN100-GUEST"
        set interface "agg-core"
        set vlanid 100
        set ip 10.20.100.254 255.255.255.0
    next
    edit "VLAN200-WIFI"
        set interface "agg-core"
        set vlanid 200
        set ip 10.20.200.254 255.255.255.0
    next
    edit "VLAN300-CAMERAS"
        set interface "agg-core"
        set vlanid 300
        set ip 10.20.300.254 255.255.255.0
    next
    edit "VLAN1000-MERDOUILLE"
        set interface "agg-core"
        set vlanid 1000
        set ip 10.20.0.254 255.255.255.0
    next
end
